<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[STEP1]]>
    </line>
    <line>
      <![CDATA[STEP2]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="11346" started-at="2017-07-31T14:15:24Z" finished-at="2017-07-31T14:15:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11346" started-at="2017-07-31T14:15:24Z" finished-at="2017-07-31T14:15:36Z">
      <class name="atu_reporte.NewTest">
        <test-method status="PASS" signature="Properties()[pri:0, instance:atu_reporte.NewTest@6500df86]" name="Properties" is-config="true" duration-ms="62" started-at="2017-07-31T19:45:24Z" finished-at="2017-07-31T19:45:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Properties -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:atu_reporte.NewTest@6500df86]" name="beforeTest" is-config="true" duration-ms="141" started-at="2017-07-31T19:45:24Z" finished-at="2017-07-31T19:45:24Z">
          <reporter-output>
            <line>
              <![CDATA[STEP1]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="Launch()[pri:1, instance:atu_reporte.NewTest@6500df86]" name="Launch" duration-ms="10926" started-at="2017-07-31T19:45:24Z" finished-at="2017-07-31T19:45:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at atu_reporte.NewTest.Launch(NewTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:atu_reporte.NewTest@6500df86]" name="afterTest" is-config="true" duration-ms="241" started-at="2017-07-31T19:45:35Z" finished-at="2017-07-31T19:45:36Z">
          <reporter-output>
            <line>
              <![CDATA[STEP2]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- atu_reporte.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
