<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 19" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="E:\Sourabh_Selenium\Sel\Selenium_python\Base\Test1.py" status="error" test="Test1" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\Ideliver\.p2\pool\plugins\org.python.pydev.core_6.3.2.201803171248\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "E:/Sourabh_Selenium/Sel/Selenium_python/Base\Test1.py", line 7, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
ERROR: Module: Test1 could not be imported (file: E:\Sourabh_Selenium\Sel\Selenium_python\Base\Test1.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Selenium_python Test1.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
