<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 20" tests="1" total_time="Finished in: 6.38 secs."/>
<test location="E:\Sourabh_Selenium\Sel\Selenium_python\Base\Test1.py" status="error" test="Test.testName" time="">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "E:\Sourabh_Selenium\Sel\Selenium_python\Base\Test1.py", line 26, in testName
    driver.find_element_by_name("userName").send_keys("agent")
  File "C:\Users\Ideliver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 487, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "C:\Users\Ideliver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 955, in find_element
    'value': value})['value']
  File "C:\Users\Ideliver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Ideliver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.37.543627 (63642262d9fb93fb4ab52398be4286d844092a5e),platform=Windows NT 6.1.7601 SP1 x86_64)

]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Selenium_python Test1.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
